tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"

brew "font-hack-nerd-font"
brew "git"
brew "lf"
brew "fzf"
brew "neovim"
brew "tmux"
brew "reattach-to-user-namespace"
brew "tree"
brew "wget"
brew "zsh"

cask "alfred"
cask "hiddenbar"
cask "rectangle"
