#!/bin/bash
set -euo pipefail

source "$DOTFILES_ROOT/scripts/common.sh"

setup_symlinks() {
  info "setting up dotfiles"

  find -H "$DOTFILES_ROOT" -maxdepth 2 -name 'setup.sh' | while read -r src
  do
    source "${src}"
  done

  success "dotfiles setup complete"
}

link_file () {
  local src=$1 dst=$2
  rm -rf "$dst"
  ln -sf "${src}" "${dst}"
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' | while read -r src
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done

  for src in "$DOTFILES_ROOT"/config/*/
  do
    if [[ -d "$src" ]]; then
      dst="$HOME/.config/$(basename "${src}")"
      link_file "$src" "$dst"
    fi
  done
}

pushd "$DOTFILES_ROOT"
setup_symlinks
install_dotfiles
popd

success 'All installed!'
