#!/bin/bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "› brew bundle"
brew bundle

echo "› ./macos-setting.sh"
source macos-setting.sh

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done