# Basic options
set -g default-terminal "xterm-256color"
set-option -g default-shell zsh
set -g mouse on
set -g allow-rename off
set -g history-limit 10000
set-window-option -g xterm-keys on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Option-arrow without prefix
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

# # Select Pane
# bind -n M-1 select-pane -t 1
# bind -n M-2 select-pane -t 2
# bind -n M-3 select-pane -t 3
# bind -n M-4 select-pane -t 4
# bind -n M-5 select-pane -t 5
# bind -n M-6 select-pane -t 6
# bind -n M-7 select-pane -t 7
# bind -n M-8 select-pane -t 8
# bind -n M-9 select-pane -t 9

# Clipboard (osx)
set -g default-command "reattach-to-user-namespace -l zsh"

# Reloading
bind C-r source-file ~/.tmux.conf \; display-message "Reloading ~/.tmux.conf"
