set-option -g history-limit 100000

#if-shell 'uname | grep -q Darwin' 'set -g default-terminal "xterm-256color"'
#if-shell 'uname | grep -q Linux' 'set -g default-terminal "tmux-256color"'
#set-option -sa terminal-overrides ",*256col*:Tc"
set -g default-terminal "xterm-256color"

### Basic options
set -g mouse on
set -g allow-rename off
set -g history-limit 10000
set-window-option -g xterm-keys on
set-option -g allow-rename off

# System clipboard
set -g set-clipboard off

# Monitoring
setw -g monitor-activity on
set -g visual-activity off
setw -g monitor-silence 0

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows when one is deleted
set-option -g renumber-windows 0

# Default shell
set-option -g default-shell /bin/zsh

# Disable right-click menu in tmux 3.0
unbind-key -T root MouseDown3Pane

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# tmux messages are displayed for 4 seconds
set -g display-time 4000

# Focus events enabled for terminals that support them
set -g focus-events on

#### Key bindings
set-window-option -g mode-keys vi

# Copy and Paste
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# split panes using | and -
unbind -T prefix '"'
bind-key -T prefix | split-window -h
unbind -T prefix &
bind-key -T prefix - split-window -v

# Reloading
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Open current directory
bind o run-shell "open #{pane_current_path}"

bind -r e kill-pane -a

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# broadcast
bind-key y set-window-option synchronize-panes

# look'n feel
set-option -g status-fg cyan
set-option -g status-bg black
set-option -g history-limit 64096

set -sg escape-time 10

#### COLOUR

# default statusbar colors
set-option -g status-style bg=colour235,fg=colour136,default

# default window title colors
set-window-option -g window-status-style fg=colour244,bg=colour234,dim

# active window title colors
set-window-option -g window-status-current-style fg=colour166,bg=default,bright

# pane border
set-option -g pane-border-style fg=colour235 #base02
set-option -g pane-active-border-style fg=colour136,bg=colour235

# message text
set-option -g message-style bg=colour235,fg=colour166

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

# import
if-shell "uname -s | grep Darwin" "source ~/.config/tmux/macos.conf"
source ~/.config/tmux/statusline.conf
